# Generated by cpputils-cmake.
include /home/han4n/2023-iotvar-hardware/Code/Phase_2/RPiPico_Powermeter_CPP/build/pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default.dir/flags.make
.PHONY: check-syntax
check-syntax:
	${CXX} -o /dev/null ${_FLAGS} ${_DEFINES} ${_INCLUDES}  -S ${CHK_SOURCES}